---
- name: Set login banner
  copy:
    content: |
      ╷  ╷╭┬╮╭─╮╷ ╷╭─╴╷
      │  ││││├─┤│╭╯├╴ │
      ╰─╴╵╵ ╵╵ ╵╰╯ ╰─╴╰─╴
      {{ instance }}
      
    dest: /etc/motd
    owner: root
    group: root
    mode: '0644'

- name: Display motd on zsh login
  become_user: limavel
  blockinfile:
    path: /home/limavel/.zshrc
    marker: "# {mark} MANAGED MOTD"
    block: |
      if [ -f /etc/motd ]; then cat /etc/motd; fi
    create: yes

- name: Display motd on bash login
  become_user: limavel
  blockinfile:
    path: /home/limavel/.bashrc
    marker: "# {mark} MANAGED MOTD"
    block: |
      if [ -f /etc/motd ]; then cat /etc/motd; fi
    create: yes
